FROM golang:1.16

WORKDIR /app

COPY . .

ENV \
    MONGO_DB_HOST=${MONGO_DB_HOST}\
    MONGO_DB_PORT=${MONGO_DB_PORT}\
    MONGO_DB_USER_NAME=${MONGO_DB_USER_NAME}\
    MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}\
    MONGO_DB_NAME=${MONGO_DB_NAME}\
    CODEF_PUBLIC_KEY=${CODEF_PUBLIC_KEY}\
    CODEF_CLIENT_ID=${CODEF_CLIENT_ID}\
    CODEF_CLIENT_SECRET=${CODEF_CLIENT_SECRET}

RUN go mod tidy

EXPOSE 8080

CMD ["go","run","."]