// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/business/status": {
            "get": {
                "description": "사업자번호로 매장의 상태를 조회한다.",
                "tags": [
                    "Business API"
                ],
                "summary": "휴폐업 상태 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사업자번호",
                        "name": "biz_number",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.CodefData"
                        }
                    }
                }
            }
        },
        "/deposit": {
            "get": {
                "description": "월단위 기준으로 일자별 입금금액을 조회한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deposit API"
                ],
                "summary": "일자별 입금금액 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "연도 - ex)2021",
                        "name": "year",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "월 - ex)04",
                        "name": "month",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deposit/:date": {
            "get": {
                "description": "일자 기준으로 카드사별 입금금액을 조회한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deposit API"
                ],
                "summary": "카드사별 입금금액 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "일자",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.CodefData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "CF-00000"
                },
                "extraMessage": {
                    "type": "string"
                },
                "message": {
                    "type": "string",
                    "example": "성공"
                },
                "resBusinessStatus": {
                    "type": "string",
                    "example": "부가가치세 일반과세자 입니다."
                },
                "resClosingDate": {
                    "type": "string"
                },
                "resCompanyIdentityNo": {
                    "type": "string",
                    "example": "1231212345"
                },
                "resTaxationTypeCode": {
                    "type": "string",
                    "example": "1"
                },
                "resTransferTaxTypeDate": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
